name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: novialriptide/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_7_days
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          LANGUAGE_COUNT: 10
