name: Waka Readme

on:
   workflow_dispatch: # for manual workflow trigger
   schedule:
      - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
   update-readme:
      name: WakaReadme DevMetrics
      runs-on: ubuntu-latest
      steps:
         - uses: athul/waka-readme@v0.1.8

           with:
              WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
              SHOW_TITLE: true
              BLOCK: ⣀⣄⣤⣦⣶⣷⣿
              TIME_RANGE: all_time
              SHOW_TIME: true
              SHOW_MASKED_TIME: true
              LANG_COUNT: 10
